ports:
- port: 6379 # Redis
  onOpen: ignore
- port: 5432 # PostgreSQL
  onOpen: ignore
- port: 8080 # Web Socket
  onOpen: ignore
- port: 8088 # Superset
  onOpen: open-browser

tasks:
  - init: |
      docker-compose -f docker-compose-non-dev.yml up --no-start
    command:
      docker-compose -f docker-compose-non-dev.yml up
